apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    name: dev-ingress
spec:
  rules:
  - host: cluster
    http:
      paths:
      - pathType: Prefix
        path: "/phpmyadmin"
        backend:
          service:
            name: phpmyadmin-svc
            port: 
              number: 80
