apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: db-ns
spec:
  type: ExternalName
  externalName: phpmyadmin-svc.db-ns.svc.cluster.local
  selector:
    app: phpmyadmin
  ports:
  - port: 80
    targetPort: 80
